# See https://ezcv.readthedocs.io for documentation
name: Sydney Melendres
theme: dimension
resume: true
email: sydneymelendres@gmail.com
biography: A description of yourself # This field is for writing about yourself you can add a > to span multiple lines
social:
  github: sydney-melendres
  linkedin: sydneymelendres
